# Generated by Django 5.2.4 on 2025-08-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address_line1_shippingaddress_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='shipping_user',
        ),
    ]
