# Generated by Django 5.2.5 on 2025-08-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_on_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_on_sale',
            new_name='is_sale',
        ),
    ]
