# Generated by Django 5.2.4 on 2025-08-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='order',
        ),
        migrations.RemoveField(
            model_name='return',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='return',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='return',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='return_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.return'),
        ),
    ]
